ServerEvents.recipes(event => {
  const { mods } = global.eqHelper
  const TABLE = [
    //血肉套
    ['spore:living_helmet', 'head', [['armor', 8], ['tough', 6], ['kb', 0.2], ['maxhp', 10], ['maxhp', 0.125, 2], ['thermal', 6], ['head', 0.5], ['atk', 0.1, 2]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:living_helmet', 'fib:bio_equipment_module'],
    ['spore:living_chest', 'chest', [['armor', 18], ['tough', 6], ['kb', 0.2], ['maxhp', 10], ['maxhp', 0.125, 2], ['thermal', 6], ['chest', 0.5], ['atk', 0.1, 2]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:living_chest', 'fib:bio_equipment_module'],
    ['spore:living_pants', 'legs', [['armor', 20], ['tough', 6], ['kb', 0.2], ['maxhp', 10], ['maxhp', 0.125, 2], ['thermal', 6], ['legs', 0.5], ['atk', 0.1, 2]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:living_pants', 'fib:bio_equipment_module'],
    ['spore:living_boots', 'feet', [['armor', 8], ['tough', 6], ['kb', 0.2], ['maxhp', 10], ['maxhp', 0.125, 2], ['thermal', 6], ['feet', 0.5], ['atk', 0.1, 2]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:living_boots', 'fib:bio_equipment_module'],
    //甲壳套装
    ['spore:plated_helmet', 'head', [['armor', 16], ['tough', 4], ['kb', 0.2], ['atk', 0.1, 2], ['maxhp', 10], ['maxhp', 0.125, 2], ['thermal', 2], ['head', 0.5]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:plated_helmet', 'fib:bio_equipment_module'],
    ['spore:plated_chest', 'chest', [['armor', 36], ['tough', 4], ['kb', 0.2], ['atk', 0.1, 2], ['maxhp', 10], ['maxhp', 0.125, 2], ['thermal', 2], ['chest', 0.5]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:plated_chest', 'fib:bio_equipment_module'],
    ['spore:plated_pants', 'legs', [['armor', 24], ['tough', 4], ['kb', 0.2], ['atk', 0.1, 2], ['maxhp', 10], ['maxhp', 0.125, 2], ['thermal', 2], ['legs', 0.5]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:plated_pants', 'fib:bio_equipment_module'],
    ['spore:plated_boots', 'feet', [['armor', 12], ['tough', 4], ['kb', 0.2], ['atk', 0.1, 2], ['maxhp', 10], ['maxhp', 0.125, 2], ['thermal', 2], ['feet', 0.5]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:plated_boots', 'fib:bio_equipment_module'],
    //活体套
    ['spore:inf_helmet', 'head', [['armor', 24], ['tough', 10], ['kb', 0.5], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.15, 2], ['thermal', 8], ['head', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_helmet', 'fib:bio_equipment_module'],
    ['spore:inf_chest', 'chest', [['armor', 52], ['tough', 10], ['kb', 0.5], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.15, 2], ['thermal', 8], ['chest', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_chest', 'fib:bio_equipment_module'],
    ['spore:inf_pants', 'legs', [['armor', 40], ['tough', 10], ['kb', 0.5], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.15, 2], ['thermal', 8], ['legs', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_pants', 'fib:bio_equipment_module'],
    ['spore:inf_boots', 'feet', [['armor', 20], ['tough', 10], ['kb', 0.5], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.15, 2], ['thermal', 8], ['feet', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_boots', 'fib:bio_equipment_module'],
    //重构活体套
    ['spore:inf_up_helmet', 'head', [['armor', 24], ['tough', 10], ['kb', 0.5], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.15, 2], ['thermal', 8], ['head', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_up_helmet', 'fib:bio_equipment_module'],
    ['spore:inf_up_chest', 'chest', [['armor', 52], ['tough', 10], ['kb', 0.5], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.15, 2], ['thermal', 8], ['chest', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_up_chest', 'fib:bio_equipment_module'],
    ['spore:inf_up_pants', 'legs', [['armor', 40], ['tough', 10], ['kb', 0.5], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.15, 2], ['thermal', 8], ['legs', 0.6], ['move', 0.3, 2], ['step', 1.5]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_up_pants', 'fib:bio_equipment_module'],
    ['spore:inf_up_boots', 'feet', [['armor', 20], ['tough', 10], ['kb', 0.5], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.15, 2], ['thermal', 8], ['feet', 0.6], ['swim', 1, 2]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_up_boots', 'fib:bio_equipment_module'],
    //生物炼金套装
    ['biomancy:acolyte_armor_helmet', 'head', [['armor', 8], ['tough', 6], ['kb', 0.5], ['atk', 0.25, 2], ['maxhp', 5], ['maxhp', 0.05, 2], ['thermal', 8], ['head', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:acolyte_armor_helmet', 'fib:bio_equipment_module'],
    ['biomancy:acolyte_armor_chestplate', 'chest', [['armor', 24], ['tough', 6], ['kb', 0.5], ['atk', 0.25, 2], ['maxhp', 5], ['maxhp', 0.05, 2], ['thermal', 8], ['chest', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:acolyte_armor_chestplate', 'fib:bio_equipment_module'],
    ['biomancy:acolyte_armor_leggings', 'legs', [['armor', 20], ['tough', 6], ['kb', 0.5], ['atk', 0.25, 2], ['maxhp', 5], ['maxhp', 0.05, 2], ['thermal', 8], ['legs', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:acolyte_armor_leggings', 'fib:bio_equipment_module'],
    ['biomancy:acolyte_armor_boots', 'feet', [['armor', 8], ['tough', 6], ['kb', 0.5], ['atk', 0.25, 2], ['maxhp', 5], ['maxhp', 0.05, 2], ['thermal', 8], ['feet', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:acolyte_armor_boots', 'fib:bio_equipment_module'],
    //战士套装
    ['biomancy:warrior_armor_helmet', 'head', [['armor', 12], ['tough', 8], ['kb', 0.5], ['atk', 0.25, 2], ['maxhp', 5], ['maxhp', 0.05, 2], ['thermal', 8], ['head', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:warrior_armor_helmet', 'fib:bio_equipment_module'],
    ['biomancy:warrior_armor_chestplate', 'chest', [['armor', 30], ['tough', 8], ['kb', 0.5], ['atk', 0.25, 2], ['maxhp', 5], ['maxhp', 0.05, 2], ['thermal', 8], ['chest', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:warrior_armor_chestplate', 'fib:bio_equipment_module'],
    ['biomancy:warrior_armor_leggings', 'legs', [['armor', 26], ['tough', 8], ['kb', 0.5], ['atk', 0.25, 2], ['maxhp', 5], ['maxhp', 0.05, 2], ['thermal', 8], ['legs', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:warrior_armor_leggings', 'fib:bio_equipment_module'],
    ['biomancy:warrior_armor_boots', 'feet', [['armor', 12], ['tough', 8], ['kb', 0.5], ['atk', 0.25, 2], ['maxhp', 5], ['maxhp', 0.05, 2], ['thermal', 8], ['feet', 0.6]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:warrior_armor_boots', 'fib:bio_equipment_module'],
    //血肉套
    ['spore:living_helmet', 'head', [['armor', 12], ['tough', 9], ['kb', 0.3], ['maxhp', 15], ['maxhp', 0.1875, 2], ['thermal', 9], ['head', 0.75], ['atk', 0.15, 2]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:living_helmet', 'fib:bio_equipment_module_0'],
    ['spore:living_chest', 'chest', [['armor', 27], ['tough', 9], ['kb', 0.3], ['maxhp', 15], ['maxhp', 0.1875, 2], ['thermal', 9], ['chest', 0.75], ['atk', 0.15, 2]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:living_chest', 'fib:bio_equipment_module_0'],
    ['spore:living_pants', 'legs', [['armor', 30], ['tough', 9], ['kb', 0.3], ['maxhp', 15], ['maxhp', 0.1875, 2], ['thermal', 9], ['legs', 0.75], ['atk', 0.15, 2]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:living_pants', 'fib:bio_equipment_module_0'],
    ['spore:living_boots', 'feet', [['armor', 12], ['tough', 9], ['kb', 0.3], ['maxhp', 15], ['maxhp', 0.1875, 2], ['thermal', 9], ['feet', 0.75], ['atk', 0.15, 2]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:living_boots', 'fib:bio_equipment_module_0'],
    //甲壳套装
    ['spore:plated_helmet', 'head', [['armor', 24], ['tough', 6], ['kb', 0.3], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.1875, 2], ['thermal', 3], ['head', 0.75]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:plated_helmet', 'fib:bio_equipment_module_0'],
    ['spore:plated_chest', 'chest', [['armor', 54], ['tough', 6], ['kb', 0.3], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.1875, 2], ['thermal', 3], ['chest', 0.75]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:plated_chest', 'fib:bio_equipment_module_0'],
    ['spore:plated_pants', 'legs', [['armor', 36], ['tough', 6], ['kb', 0.3], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.1875, 2], ['thermal', 3], ['legs', 0.75]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:plated_pants', 'fib:bio_equipment_module_0'],
    ['spore:plated_boots', 'feet', [['armor', 18], ['tough', 6], ['kb', 0.3], ['atk', 0.15, 2], ['maxhp', 15], ['maxhp', 0.1875, 2], ['thermal', 3], ['feet', 0.75]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:plated_boots', 'fib:bio_equipment_module_0'],
    //活体套
    ['spore:inf_helmet', 'head', [['armor', 36], ['tough', 15], ['kb', 0.75], ['atk', 0.225, 2], ['maxhp', 22.5], ['maxhp', 0.225, 2], ['thermal', 12], ['head', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_helmet', 'fib:bio_equipment_module_0'],
    ['spore:inf_chest', 'chest', [['armor', 78], ['tough', 15], ['kb', 0.75], ['atk', 0.225, 2], ['maxhp', 22.5], ['maxhp', 0.225, 2], ['thermal', 12], ['chest', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_chest', 'fib:bio_equipment_module_0'],
    ['spore:inf_pants', 'legs', [['armor', 60], ['tough', 15], ['kb', 0.75], ['atk', 0.225, 2], ['maxhp', 22.5], ['maxhp', 0.225, 2], ['thermal', 12], ['legs', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_pants', 'fib:bio_equipment_module_0'],
    ['spore:inf_boots', 'feet', [['armor', 30], ['tough', 15], ['kb', 0.75], ['atk', 0.225, 2], ['maxhp', 22.5], ['maxhp', 0.225, 2], ['thermal', 12], ['feet', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_boots', 'fib:bio_equipment_module_0'],
    //重构活体套
    ['spore:inf_up_helmet', 'head', [['armor', 36], ['tough', 15], ['kb', 0.75], ['atk', 0.225, 2], ['maxhp', 22.5], ['maxhp', 0.225, 2], ['thermal', 12], ['head', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_up_helmet', 'fib:bio_equipment_module_0'],
    ['spore:inf_up_chest', 'chest', [['armor', 78], ['tough', 15], ['kb', 0.75], ['atk', 0.225, 2], ['maxhp', 22.5], ['maxhp', 0.225, 2], ['thermal', 12], ['chest', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_up_chest', 'fib:bio_equipment_module_0'],
    ['spore:inf_up_pants', 'legs', [['armor', 60], ['tough', 15], ['kb', 0.75], ['atk', 0.225, 2], ['maxhp', 22.5], ['maxhp', 0.225, 2], ['thermal', 12], ['legs', 0.9], ['move', 0.45, 2], ['step', 2.25]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_up_pants', 'fib:bio_equipment_module_0'],
    ['spore:inf_up_boots', 'feet', [['armor', 30], ['tough', 15], ['kb', 0.75], ['atk', 0.225, 2], ['maxhp', 22.5], ['maxhp', 0.225, 2], ['thermal', 12], ['feet', 0.9], ['swim', 1.5, 2]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'spore:inf_up_boots', 'fib:bio_equipment_module_0'],
    //生物炼金套装
    ['biomancy:acolyte_armor_helmet', 'head', [['armor', 12], ['tough', 9], ['kb', 0.75], ['atk', 0.375, 2], ['maxhp', 7.5], ['maxhp', 0.075, 2], ['thermal', 12], ['head', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:acolyte_armor_helmet', 'fib:bio_equipment_module_0'],
    ['biomancy:acolyte_armor_chestplate', 'chest', [['armor', 36], ['tough', 9], ['kb', 0.75], ['atk', 0.375, 2], ['maxhp', 7.5], ['maxhp', 0.075, 2], ['thermal', 12], ['chest', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:acolyte_armor_chestplate', 'fib:bio_equipment_module_0'],
    ['biomancy:acolyte_armor_leggings', 'legs', [['armor', 30], ['tough', 9], ['kb', 0.75], ['atk', 0.375, 2], ['maxhp', 7.5], ['maxhp', 0.075, 2], ['thermal', 12], ['legs', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:acolyte_armor_leggings', 'fib:bio_equipment_module_0'],
    ['biomancy:acolyte_armor_boots', 'feet', [['armor', 12], ['tough', 9], ['kb', 0.75], ['atk', 0.375, 2], ['maxhp', 7.5], ['maxhp', 0.075, 2], ['thermal', 12], ['feet', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:acolyte_armor_boots', 'fib:bio_equipment_module_0'],
    //战士套
    ['biomancy:warrior_armor_helmet', 'head', [['armor', 16], ['tough', 10], ['kb', 0.75], ['atk', 0.375, 2], ['maxhp', 7.5], ['maxhp', 0.075, 2], ['thermal', 12], ['head', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:warrior_armor_helmet', 'fib:bio_equipment_module_0'],
    ['biomancy:warrior_armor_chestplate', 'chest', [['armor', 42], ['tough', 10], ['kb', 0.75], ['atk', 0.375, 2], ['maxhp', 7.5], ['maxhp', 0.075, 2], ['thermal', 12], ['chest', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:warrior_armor_chestplate', 'fib:bio_equipment_module_0'],
    ['biomancy:warrior_armor_leggings', 'legs', [['armor', 36], ['tough', 10], ['kb', 0.75], ['atk', 0.375, 2], ['maxhp', 7.5], ['maxhp', 0.075, 2], ['thermal', 12], ['legs', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:warrior_armor_leggings', 'fib:bio_equipment_module_0'],
    ['biomancy:warrior_armor_boots', 'feet', [['armor', 16], ['tough', 10], ['kb', 0.75], ['atk', 0.375, 2], ['maxhp', 7.5], ['maxhp', 0.075, 2], ['thermal', 12], ['feet', 0.9]], 'agent:{mutant_enchanting:16.0d,mutant_max_durability:80,mutant_protection:80.0d,mutant_toughness:9.0d,mutation:0}', 'biomancy:warrior_armor_boots', 'fib:bio_equipment_module_0'],
  ]
  for (const [item, slot, attrs, extra, material, module] of TABLE) {
    event.custom({ type: 'createdieselgenerators:basin_fermenting', ingredients: [{ item: module }, { item: material }], processingTime: 200, results: [Item.of(item, extra ? mods(slot, attrs, extra) : mods(slot, attrs))], heatRequirement: 'superheated' })
  }
})
