
["Common Weapon/ 一般武器设置"]
	#The Evil Sword can use skill / 衰恶之剑是否可以使用技能
	EvilSwordSkill = true

["Latiao Weapon/ 辣条武器设置"]
	#Maximum attack damage of Fouroseven Latiao Club / 肆零柒·辣棒的最大攻击伤害
	#Range: > 21
	MaxAttackDamageFourosevenLatiaoClub = 500
	#Allow the Fouroseven Latiao Club to announce messages upon upgrade / 肆零柒·辣棒升级时是否会播报信息
	AnnounceUpgradeFourosevenLatiaoClub = true

