#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=curio;size=0", "id=skill;size=3", "id=blood;size=8", "id=organ;size=0"]

