#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Mar 22 00:43:16 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=MakeUp-UltraFast-9.3h.zip
enableShaders=true
