ServerEvents.recipes(event => {
  const { mods } = global.eqHelper
  const TABLE = [
    ['goety_revelation:apocalyptium_chestplate', 'chest', [['armor', 26], ['tough', 10], ['kb', 0.6], ['thermal', 2], ['chest', 0.35], ['soulDec', 0.32, 2], ['soulInc', 0.32, 2], ['soulSteal', 0.32, 2], ['spellPow', 2], ['spellMul', 0.2], ['castDur', 0.15], ['spellCd', 0.15]], null, 'goety_revelation:apocalyptium_chestplate', 1000, 10],
    ['goety_revelation:apocalyptium_helmet', 'head', [['armor', 16], ['tough', 10], ['kb', 0.6], ['thermal', 2], ['soulDec', 0.32, 2], ['soulInc', 0.32, 2], ['soulSteal', 0.32, 2], ['spellPow', 2], ['spellMul', 0.2], ['castDur', 0.15], ['spellCd', 0.15]], null, 'goety_revelation:apocalyptium_helmet', 1000, 10],
    ['goety_revelation:apocalyptium_leggings', 'legs', [['armor', 24], ['tough', 10], ['kb', 0.6], ['thermal', 2], ['soulDec', 0.32, 2], ['soulInc', 0.32, 2], ['soulSteal', 0.32, 2], ['spellPow', 2], ['spellMul', 0.2], ['castDur', 0.15], ['spellCd', 0.15]], null, 'goety_revelation:apocalyptium_leggings', 1000, 10],
    ['goety_revelation:apocalyptium_boots', 'feet', [['armor', 16], ['tough', 10], ['kb', 0.6], ['thermal', 2], ['soulDec', 0.32, 2], ['soulInc', 0.32, 2], ['soulSteal', 0.32, 2], ['spellPow', 2], ['spellMul', 0.2], ['castDur', 0.15], ['spellCd', 0.15]], null, 'goety_revelation:apocalyptium_boots', 1000, 10],
    //神经蚀刻
    ['goety_revelation:spider_darkmage_helmet', 'head', [['armor', 8], ['tough', 8], ['kb', 0.35], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 3], ['spellMul', 0.3], ['castDur', 0.2], ['spellCd', 0.2]], null, 'goety_revelation:spider_darkmage_helmet', 1000, 10],
    ['goety_revelation:spider_darkmage_chestplate', 'chest', [['armor', 20], ['tough', 8], ['kb', 0.35], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 3], ['spellMul', 0.3], ['castDur', 0.2], ['spellCd', 0.2]], null, 'goety_revelation:spider_darkmage_chestplate', 1000, 10],
    ['goety_revelation:spider_darkmage_leggings', 'legs', [['armor', 16], ['tough', 8], ['kb', 0.35], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 3], ['spellMul', 0.3], ['castDur', 0.2], ['spellCd', 0.2]], null, 'goety_revelation:spider_darkmage_leggings', 1000, 10],
    ['goety_revelation:spider_darkmage_boots', 'feet', [['armor', 8], ['tough', 8], ['kb', 0.35], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 3], ['spellMul', 0.3], ['castDur', 0.2], ['spellCd', 0.2], ['step', 1]], null, 'goety_revelation:spider_darkmage_boots', 1000, 10],
    //渊魄黑魔法师
    ['goety_revelation:spectre_darkmage_helmet', 'head', [['armor', 8], ['tough', 8], ['kb', 0.35], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 3], ['spellMul', 0.3], ['castDur', 0.2], ['spellCd', 0.2]], null, 'goety_revelation:spectre_darkmage_helmet', 1000, 10],
    ['goety_revelation:spectre_darkmage_chestplate', 'chest', [['armor', 20], ['tough', 8], ['kb', 0.35], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 3], ['spellMul', 0.3], ['castDur', 0.2], ['spellCd', 0.2]], null, 'goety_revelation:spectre_darkmage_chestplate', 1000, 10],
    ['goety_revelation:spectre_darkmage_leggings', 'legs', [['armor', 16], ['tough', 8], ['kb', 0.35], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 3], ['spellMul', 0.3], ['castDur', 0.2], ['spellCd', 0.2]], null, 'goety_revelation:spectre_darkmage_leggings', 1000, 10],
    ['goety_revelation:spectre_darkmage_boots', 'feet', [['armor', 8], ['tough', 8], ['kb', 0.35], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 3], ['spellMul', 0.3], ['castDur', 0.2], ['spellCd', 0.2]], null, 'goety_revelation:spectre_darkmage_boots', 1000, 10],
    //黑暗套
    ['goety:dark_helmet', 'head', [['armor', 8], ['tough', 6], ['kb', 0.5], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 1], ['spellMul', 0.1], ['castDur', 0.15], ['spellCd', 0.15]], null, 'goety:dark_helmet', 1000, 10],
    ['goety:dark_chestplate', 'chest', [['armor', 24], ['tough', 6], ['kb', 0.5], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 1], ['spellMul', 0.1], ['castDur', 0.15], ['spellCd', 0.15]], null, 'goety:dark_chestplate', 1000, 10],
    ['goety:dark_leggings', 'legs', [['armor', 16], ['tough', 6], ['kb', 0.5], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 1], ['spellMul', 0.1], ['castDur', 0.15], ['spellCd', 0.15]], null, 'goety:dark_leggings', 1000, 10],
    ['goety:dark_boots', 'feet', [['armor', 8], ['tough', 6], ['kb', 0.5], ['thermal', 1], ['soulDec', 0.2, 2], ['soulInc', 0.2, 2], ['soulSteal', 0.2, 2], ['spellPow', 1], ['spellMul', 0.1], ['castDur', 0.15], ['spellCd', 0.15]], null, 'goety:dark_boots', 1000, 10],
  ]
  for (const [item, slot, attrs, extra, activation, soulCost, duration] of TABLE) {
    event.custom({ type: 'goety:ritual', ritual_type: 'goety:craft', activation_item: { item: activation }, craftType: 'magic', research: 'fib:soul_research', soulCost: soulCost, duration: duration, ingredients: [{ item: 'fib:echo_equipment_module' }], result: Item.of(item, extra ? mods(slot, attrs, extra) : mods(slot, attrs)) })
  }
})
