ServerEvents.recipes(event => {

    event.stonecutting(
        Item.of('spore:acidic_sack'),
        'spore:biomass_block'
    )
    event.stonecutting(
        Item.of('spore:glowshroom'),
        'spore:biomass_block'
    )
    event.stonecutting(
        Item.of('spore:bile_lump'),
        'spore:biomass_block'
    )
    event.stonecutting(
        Item.of('spore:drowned_lump'),
        'spore:biomass_block'
    )
    event.stonecutting(
        Item.of('spore:fang_lump'),
        'spore:biomass_block'
    )
    event.stonecutting(
        Item.of('spore:lungs'),
        'spore:biomass_block'
    )
    event.stonecutting(
        Item.of('spore:vocals'),
        'spore:biomass_block'
    )
    event.stonecutting(
        Item.of('spore:hand'),
        'spore:biomass_block'
    )
    event.stonecutting(
        Item.of('spore:rotten_scraps'),
        'spore:rotten_planks'
    )
    event.stonecutting(
        Item.of('spore:rotten_branch'),
        'spore:rotten_planks'
    )
    event.stonecutting(
        Item.of('spore:rotten_bush'),
        'spore:rotten_planks'
    )
    event.stonecutting(
        Item.of('spore:rotten_grass'),
        'spore:rotten_planks'
    )
    event.stonecutting(
        Item.of('spore:rotten_crops'),
        'spore:rotten_planks'
    )
    event.stonecutting(
        Item.of('spore:rotten_fern'),
        'spore:rotten_planks'
    )
});
